### ISSUE TITLE
Single point simulations

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1198]
We are discussing deprecating the PTCLM toolchain (as the toolchain is being remade).  This will be replaced with the faster scripts that pull atmospheric forcing, surface dataset and domain file with python scripts from @swensosc (currently in tools/contrib) that  can be written over / modified as  needed.

Are there features / functions that we'll lose by doing this?   Specifically, @olyson how do you set up single point urban simulations?
If / when we go down this route we'll need to:
- [x] modify singlept.py script, #1352 
  - update singlept.py script to python3  (currently python2)
  - develop testing to  bring this out of /tools/contrib?
- [x] Create new modify_singlept_NEON script that reads in NEON observations, #1353 
   - modify dominant PFTs & soil properties
   - eventually modify parameter file (foliar C:N, allocation, others?)
- [x] Batch process multiple sites, #1354 
  - communicate with PLUMBER2 & NEON for distributing tower forcing data with CTSM
  - improve @olyson .csh script that can simulate multiple sites at once. This may need  to be done more generically to run  in  the cloud.
- [x] Provide jupyter notebooks for sample analyses, #1355  
- [ ] Update users  guide to reflect this new workflow, #1494

*This can be addressed by the SE supported by  NCAR-NEON funding*

**Comment by swensosc** [comment]
my understanding was that the reason ptclm takes as long as it does is due
to its use of mapping files.  Another way forward would be to write a
script that would go to the raw data files and just grab the values at the
closest point.  This would be a little work, but it would preclude the need
to point to an existing surface data file.  It would also represent our
'best guess' for the site, rather than getting values that have been
averaged over a much larger area.

**Comment by olyson** [comment]
For urban sites, I generally just start with an existing surface dataset/domain file and edit using NCL.

**Comment by billsacks** [comment]
> my understanding was that the reason ptclm takes as long as it does is due to its use of mapping files. Another way forward would be to write a script that would go to the raw data files and just grab the values at the closest point. This would be a little work, but it would preclude the need to point to an existing surface data file. It would also represent our 'best guess' for the site, rather than getting values that have been averaged over a much larger area.

That's a good point, @swensosc . @ekluzek @slevisconsulting @negin513 I wonder if it's worth considering an option to the new toolchain that just does a nearest neighbor mapping rather than a conservative mapping. If it's easy to do, we could make this the default for single-point runs, but I'm starting to wonder if it would be a useful option to have in general. My impression is that it should be easy to implement this, since I think it would just mean changing one argument to the esmf regridding routine. I guess, though, the main value in doing this would be to speed the process, so it's only worth doing if it actually does speed the process significantly. (I'm suggesting this instead of a custom script just to keep the process consistent and to make it easier for us to implement that option, under the assumption that ESMF's nearest neighbor mapping would be about as efficient as any custom script we wrote.)

I don't think this would work for the topography standard deviation which is computed from the 1 km dataset, though. There may be other cases that don't work as intended in mksurfdata_map if using nearest neighbor, but off-hand I can't think of others.

**Comment by ekluzek** [comment]
@billsacks yes I like this idea better. @swensosc creating a script to handle all dozen of the input files to mksurfdata sounds a bit problematic. As @billsacks points out it would need to be synchronized with the mksurfdata_map code as well. If we thought we wanted to replace the mksurfdata_map code with a script (which isn't a bad thing to consider) that would seem better. In the long run having a script replace mksurfdata_map would be a good goal to make it easier to work with -- but that would be a big project.

But, I really like the idea of building into the planned toolchain the ability to get nearest neighbor mapping. That should be tons faster. And yes the standard dev of the 1km datasets is the only thing I can think of that wouldn't work either. But, you really wouldn't get a good value for that for a single point anyway. Maybe that should just be assigned an arbitrary value for single point sites? @swensosc what would be a good way to set this value for a tower site?

I know soil color is handled in a strange way, but I think the nearest neighbor method should work for it.

**Comment by ekluzek** [comment]
@olyson we still have mksurfdata create datasets for MexicoCity, Vancouver-CAN, Camden-NJ and urbanc_alpha. And the model is setup to run these out of the box. Is there still a need to be able to do this? Or can these special cases be removed? We do create these with each update of the surface datasets. If we didn't need to do that, we could remove some complexity.

We also have the capacity to create a special urban test case called asphalt-jungle (with no permeable road). I don't think we run that test anymore, so we could likely remove that.

**Comment by olyson** [comment]
I think it could be useful to keep at least one of these as part of the test suite?  I think you could remove all but Camden-NJ, as I've found that to be useful very recently.

**Comment by swensosc** [comment]
The standard deviation of the topography is used in the fractional snow
cover parameterization.  For site level, a uniform snow cover is more
appropriate so I usually set the standard dev to 20.  This results in a
steep curve and a nearly uniform snow cover fraction.  I also usually set
fmax to zero, which essentially inactivates the saturated fraction
parameterization, which is another subgrid parameterization that isn't
appropriate for most site level simulations.

**Comment by dlawrenncar** [comment]
This raises the question about whether or not these types of things should
somehow get set by default for single point runs, which I guess might be
possible if a user uses a compset to setup a run.

**Comment by swensosc** [comment]
sometimes I use single point runs when debugging a global run.  in that
case, it is still useful to have a script that just pulls a point from a
global run, and keeps those parameters identical.

**Comment by ekluzek** [comment]
@danicalombardozzi @wwieder @negin513 @jedwards4b and myself met today and talked about this some in context of the work with NEON. I proposed that both NEON and supported, unsupported sites be setup to use user-mod-directories to get the settings right. The more highly supported sites (like NEON) would have fewer things in the user-mod directory and mostly encoded in XML. For an unsupported tower site the surface datasets would be put in the user_nl_clm file.

So for NEON you'd do this to run the specific Yellowstone NEON tower site...

`./create_newcase --compset I1PtClm50Bgc --res CLM_USRDAT --user-mods-dir neon/YELL`


For a supported PLUMBER2 site you'd have something similar with maybe plumber2/HARV for the user-mod directory for it. The difference to above is that there would likely be more settings in the user-mod directory itself rather than encapsulated in the XML files.

When a user runs the singlept script to create data for an unsupported site it would be something like this...

`./create_newcase --compset I1PtClm50Bgc --res CLM_USRDAT --user-mods-dir mydirectoryIcreated`

Where the output of the singlept script is to create a user-mod directory that the use can point to run their case.

By, using a user-mod-directory in each case it makes the workflow more similar between all of the options. The compset and resolution above already exist so there we are just taking advantage of something that's already there.

**Comment by slevisconsulting** [comment]
In the context of the NEON work discussed above, @negin513 mentioned to me that the question was posed whether to generate surface datasets for such site simulations on the fly each time one of these simulations is performed. Assuming I understood the issue correctly, my recommendation would be to generate the surface datasets only once to avoid the risk of slightly different copies of the same surface dataset inadvertently creeping into the project. Generating the surface datasets once will contribute to consistency in the performed simulations.
(If I misunderstood the issue, pls disregard my comment.)

**Comment by danicalombardozzi** [comment]
@slevisconsulting: Thanks for your input! We settled on making the surface datasets once rather than on the fly.

**Comment by ekluzek** [comment]
@jedwards4b has come up with a great idea to simplify things to eliminate domain files by overloading PTS_MODE in cime to get the latitude and longitude from the xml variables PTS_LAT and PTS_LON. Domain files can be helpful for regional grids to give the size and area and mask of each gridcell. But, for single point sites none of those things are really meaningful.

The cime PR for this is here...

 https://github.com/ESMCI/cime/pull/3868

**Comment by ekluzek** [comment]
PR #1309 brings in the changes so that domain files are not needed when using the NUOPC coupler

**Comment by wwieder** [comment]
I'm also going to assign @glemieux and @rgknox to this issue, as bringing in FATES functionality for single point cases would also be nice with this effort (but also maybe warrant a specific issue to track).

**Comment by rgknox** [comment]
Working through some tests at one of our NGEE-Tropics sites for FATES, BCI panama.

In my typical workflow, when running a RES=CLM_USRDAT, I also use:

> ./xmlchange DATM_MODE=CLM1PT

This generates a file: run/datm.streams.txt.CLM1PT.CLM_USRDAT

My build process doesn't seem to complain about any of my xml settings, but it can't find the stream file.  Is this deprecated, or is there a new way to import site level met drivers?

**Comment by ekluzek** [comment]
@rgknox there's a bug in the latest cime that we have in the latest CTSM that causes this to not work. So consider this non functional until I get it to work. The cime issue is here...

https://github.com/ESMCI/cime/issues/3905

**Comment by ekluzek** [comment]
@rgknox a workaround I found that seems to work for me for an individual case is to set the ATM_GRID and LND_GRID in the case by hand to CLM_USRDAT with xmlchange. Try that and see if you can get your case to work. Be sure to let me know if it does.

**Comment by rgknox** [comment]
Thanks @ekluzek 

The model is still trying to find an unset fatmlndfrc file:

> Model ctsm missing file fatmlndfrc = '/raid1/lbleco/cesm/cesm_input_datasets//share/domains/UNSET'
