### ISSUE TITLE
Alternative cost functions in FUN

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1339]
New work by Tom Bytnerowicz @tbytnero generated a revised temperature function for nitrogen fixation that could replace the Houlton et al function we're currently using in FUN. https://github.com/ESCOMP/CTSM/blob/bc7c8a329da179d353ea5bbdaac0c18f68e7dada/src/biogeochem/CNFUNMod.F90#L1606

This also could be applied in FATES, @ckoven & @rgknox ?

I'm opening this issue as a place holder to record ideas about when and how to best try out the new temperature function in the model.

Definition of DONE:

- [x] Tom's NFIX by default for clm6_0
- [x] New paramfile with higher survivability and less absurd parameter choices (see https://github.com/NCAR/LMWG_dev/issues/89)
- [x] New IC files for FV09 1850 (see https://github.com/NCAR/LMWG_dev/issues/89), new ne30 1850 may be best but not available at this time
- [x] ./rimport new files as needed (slevis clarification: To resolve izumi aux_clm failures)
- [x] #2983

**Comment by slevis-lmwg** [comment]
Definition of DONE:
- [ ] Tom's NFIX by default for clm6_0
- [ ] New paramfile with higher survivability and less absurd parameter choices (see NCAR/LMWG_dev#89)
- [ ] New IC files for FV09 1850 (see NCAR/LMWG_dev#89), new ne30 1850 may be best but not available at this time

**Comment by ekluzek** [comment]
@slevis-lmwg note, I copied the definition of dove to the top post, just to make it easier to see and update.

**Comment by rgknox** [comment]
Thanks for tagging us @wwieder , yes we have wanted to get Tom's updated functions into FATES too.
