### ISSUE TITLE
Documentation of new features needed

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2113]
We have a number of new features that have been added to the model recently that should be documented in the tech note and user's guide. I've started a short list of these and tried to suggest people who can help with this.  Maybe at an upcoming meeting we can discuss how to efficiently get these contributions into our documentation?

- [ ] Crop Calendar, #1863 @samsrabin 
- [x] Excess Ice, #1787 @mvdebolskiy, see #2161
- [x] Roughness Length, #2045 @olyson, see #2134
- [ ] MIMICS, @wwieder 
- [ ] NEON, @wwieder and @TeaganKing 
- [ ] Nuopc
- [ ] User's guide clean up broken links & formatting

And more that are moving through the queue like:
- [ ] SNICAR #1861 @cenlinhe
- [ ] Dust, #1897 @dmleung 
- [x] Tillage, #2040 @samsrabin
- [x] Residue removal, #2297 @samsrabin
- [ ] Time related changes to history files (likely as a wiki)?

I'm sure there are others we need to add to this list...

**Comment by wwieder** [comment]
Thanks @mvdebolskiy, that's excellent! do we just have to 'build' the tech note again for these to changes to [show up on the wiki](https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/Soil_Snow_Temperatures/CLM50_Tech_Note_Soil_Snow_Temperatures.html#soil-and-snow-thermal-properties)?  Is there additional, practical information that should be included in the user's guide for excess ice? I'm not familiar with how to run with this feature?

@samsrabin I'm not sure if the crop calendar work belongs with other [crop model documentation ](https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.html)or under [special cases in the user's guide]? Are the crop calendars not going to be on by default for CTSM5.1 crop simulations?

**Comment by samsrabin** [comment]
That's right, @wwieder. All I've done so far is add prescribed static crop calendars, which of course don't allow prognostic seasonal shifts.

**Comment by mvdebolskiy** [comment]
> Thanks @mvdebolskiy, that's excellent! do we just have to 'build' the tech note again for these to changes to [show up on the wiki](https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/Soil_Snow_Temperatures/CLM50_Tech_Note_Soil_Snow_Temperatures.html#soil-and-snow-thermal-properties)? 
Yes.

> Is there additional, practical information that should be included in the user's guide for excess ice? I'm not familiar with how to run with this feature?

Might be. I can add an entry to the "Run with special cases" about how initialization works and additional spinup required. However, it's described in the papers linked in the tech note.

**Comment by cenlinhe** [comment]
@wwieder I am happy to contribute to the documentation for the SNICAR updates. Please let me know how I should proceed (e.g., prepare a word doc and send it to the CTSM team?) and when you will need it. Thanks!

**Comment by TeaganKing** [comment]
@wwieder Do we want to add a new [tech note](https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/index.html) section (eg, 2.33) for running with NEON? I'm not sure that it would fit under other pre-existing sections. I'd be happy to put something together for run_neon in general, as well as including some PRISM details, and make a [PR to update the tech note](https://github.com/ESCOMP/CTSM/tree/master/doc/source/tech_note).

**Comment by dlawrenncar** [comment]
I think we need to have a discussion about the crop calendars and how we
will be using this feature going forward.  Due to the large biases in some
regions in crop planting dates in CLM5, I think it is a big priority to
include a crop planting calendar for CTSM6, perhaps even if we do not allow
prognostic seasonal shifts.  Or, maybe a very simple parameterization
allowing for a shifting crop planting date could be implemented.

**Comment by samsrabin** [comment]
Definitely agree, @dlawrenncar. I'll send you et al. an email. For now, I have some ideas for "easy [prognostic] wins" in issue #1928.

**Comment by dmleung** [comment]
Hi, I can write the dust updates for the tech note too!

**Comment by mvdebolskiy** [comment]
@wwieder Are you making a PR I can contribute to, or should I just make a separate one?

**Comment by wwieder** [comment]
You can make a new one, @mvdebolskiy. thanks.

**Comment by wwieder** [comment]
Good question, @TeaganKing. I think we'll want to update the [user's guide for NEON cases in section 1.6](https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/running-single-points/index.html).  I'd imagine this may be a larger overhaul for running point and regional cases with our new workflows.  Does this make sense to others?

**Comment by olyson** [comment]
@olyson will document the surface roughness parameterization.

**Comment by mvdebolskiy** [comment]
@samsrabin  regarding history fields. [links in this section](https://github.com/ESCOMP/CTSM/blob/master/doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.rst#list-of-fields-that-can-be-added-to-your-output-history-files-by-namelist) do not work.

**Comment by samsrabin** [comment]
Marking the tillage task as done, as I've added documentation to that PR (#2040).

**Comment by mvdebolskiy** [comment]
- [ ] Update Excess Ice descriptions in User Guide after: #2465 and #2466

**Comment by samsrabin** [comment]
In TSS mini-retreat today, we talked about a need for documentation of workflows for: 
- PPE, 
- land use time series, 
- hydrology PPEs, 
- supported towers (and PPEs thereof)—running many towers concurrently on a node
- [CTSM_python_gallery](https://github.com/NCAR/ctsm_python_gallery) utilities
[Hillslope hydrology](https://github.com/ESCOMP/CTSM/pull/2425) (including a CUPiD notebook)
- Single-point and regional land-only cases—documentation is scattered and inconsistent. A lot of DiscussCESM time is spent on this. There are [four](https://github.com/ESCOMP/CTSM/issues/614) [different](https://github.com/ESCOMP/CTSM/issues/1494) [repo](https://github.com/ESCOMP/CTSM/issues/1565) [issues](https://github.com/ESCOMP/CTSM/issues/2892) about single-point docs!

**Comment by mvdebolskiy** [comment]
@samsrabin I've written the docs after for user-guide. However, they have to be changed a bit, since now it's a default option to run with excess_ice.
