### ISSUE TITLE
MIMICS todo list

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2361]
Working with @piersond and @katierocci on our MSBio project we've realized a few things should be altered in MIMICS.  This is a running list of issues to address.  Checked boxes have been evaluated in single point testing

- [x] Modify Vmax parameterization to avoid excessively large litter pools (from preliminary tests).
  - This could be evaluated further. 
- [x] Remove environmental scalars from microbial turnover (tau) calculation (causes fluxes to be unresponsive to changes in soil moisture).
- [x] Fix how the density dependent turnover parameterization is implemented in CLM-MIMICS, currently parameterized (should not be densdep-1).
Both of the isssues above are related to [this line](https://github.com/ESCOMP/CTSM/blob/c030c2342dac53d30ed419aca262db8fa7213ee6/src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90#L1292), which is repeated for oli_mic too: 
```
decomp_k(c,j,i_cop_mic) = tau_m1 *m1_conc**(mimics_densdep - 1.0_r8) * w_d_o_scalars
```
- [x] remove [NPP modification of tau](https://github.com/ESCOMP/CTSM/blob/c030c2342dac53d30ed419aca262db8fa7213ee6/src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90#L1171) (which may help with depth profiles of litter and microbial biomass)?  
  - For now this can be done on the parameter file by setting mimics_tau_mod_min & _max to one 
- [ ] Check definition of pools and modifications to fluxes, as current pool size of SOMa > SOMc, which doesn't make sense. 
![image](https://github.com/ESCOMP/CTSM/assets/8031012/5c4ff649-d5eb-4184-ae1c-5b1bdca31ee4)

**Comment by mvdebolskiy** [comment]
Tagging @elisacw, so she is up-to-date.

**Comment by wwieder** [comment]
Thanks @mvdebolskiy

**Comment by wwieder** [comment]
@slevis-lmwg I'm trying to understand why CHEM pools are so much smaller than AVAIL in the plot above.  

One thing I can't track down is the fraction of litter inputs that bypasses the microbial "filter" and goes direct to SOM pools.  This parameter was called `FI` in previous MIMICS work and was larger for structural litter (passed to chemically protected SOM) than it was for metabolic letter (passed to protected SOM).  I can't find where litter inputs enter the litter pools at all in the code, nor can I find a parameter like FI on the parameter file.  If you have some time, can we dig into this together?  Thanks in advance.

**Comment by slevis-lmwg** [comment]
I'm adding @wwieder's notes from an email here:

in CNCStateUpdate1Mod.F90, line 214
```
                  ! phenology and dynamic land cover fluxes
                  do i = i_litr_min, i_litr_max
                     cf_soil%decomp_cpools_sourcesink_col(c,j,i) = &
                          cf_veg%phenology_c_to_litr_c_col(c,j,i) * dt
                  end do
```
- [ ] I think this is where we want to send a fraction of the phenology_c_to_litr_c_col flux to SOM2 and SOM3 in MIMICS.  I'm sure some details of this aren't quite right, but something like this is what we want for MIMICS:
```
cf_soil%decomp_cpools_sourcesink_col(c,j,lit1) = (1 - mimics_fi_1) * cf_veg%phenology_c_to_litr_c_col(c,j,lit1) * dt
cf_soil%decomp_cpools_sourcesink_col(c,j,lit2) = (1 - mimics_fi_2) * cf_veg%phenology_c_to_litr_c_col(c,j,lit2) * dt

cf_soil%decomp_cpools_sourcesink_col(c,j,som3) = mimics_fi_1 * cf_veg%phenology_c_to_litr_c_col(c,j,lit1) * dt
cf_soil%decomp_cpools_sourcesink_col(c,j,som2) = mimics_fi_2 * cf_veg%phenology_c_to_litr_c_col(c,j,lit2) * dt
```
- [ ] We'll have to repeat this code for N fluxes too.
- [ ] In the testbed I'm using values of 0.005 and 0.3 for mimics_fi_1 and mimics_fi_2, respectively.  This should be a single 2d parameter on the parameter file, similar to how we have other mimics parameters.

As a separate issue, it seems like allocation to litter pools is actually being determined in CNPhenologyMod.F90 by the parameters lf_f & lf_r.  This is different to how MIMICS handles the allocation to LIT1 and LIT2 pools, but may not be worth addressing at this point.

**Comment by slevis-lmwg** [comment]
@wwieder and I agreed on the following steps:
- @wwieder will open a PR with his mods and make me collaborator
- @wwieder will add the new parameters (mimics_fi) to an already modified params file that he's working with
- @slevis-lmwg will add the code changes described above

**Comment by slevis-lmwg** [comment]
Here is my first draft of the code change in CNCStateUpdate1Mod.F90:
```
                  ! phenology and dynamic land cover fluxes
                  if (decomp_method == mimics_decomp) then
                     do i = i_litr_min, i_litr_max  ! in MIMICS these are 1 and 2
                        cf_soil%decomp_cpools_sourcesink_col(c,j,i) = (1 - mimics_fi(i)) * &
                           cf_veg%phenology_c_to_litr_c_col(c,j,i) * dt
                     end do
                     cf_soil%decomp_cpools_sourcesink_col(c,j,i_phys_som) = mimics_fi(1) * &
                        cf_veg%phenology_c_to_litr_c_col(c,j,i_met_lit) * dt
                     cf_soil%decomp_cpools_sourcesink_col(c,j,i_chem_som) = mimics_fi(2) * &
                        cf_veg%phenology_c_to_litr_c_col(c,j,i_str_lit) * dt
                  else
                     do i = i_litr_min, i_litr_max
                        cf_soil%decomp_cpools_sourcesink_col(c,j,i) = &
                             cf_veg%phenology_c_to_litr_c_col(c,j,i) * dt
                     end do
                  end if
```
...and equivalent in CNNStateUpdate1Mod.F90.

**Comment by wwieder** [comment]
looks good to me Sam.  Once you have this ready to go I'll test it out on my branch.

Easiest may be for me to use use source mods, so if you can point me to your branch / directory I'll grab the StateUpdate1Mod files to test things out.  Alternatively, I guess you can push to my PR branch and I can pull the changes onto my local branch?

**Comment by wwieder** [comment]
@slevis-lmwg is this something that can be accomplished in Sprint 3, even if it's just implementing the code mods on a branch tag that I can merge into simulations I'm running with MIMICS?  It will remove a blocker for me, but isn't super urgent as I'm on PTO next week :)

**Comment by ekluzek** [comment]
@wwieder it looks like there is more to do here. What time-line should this work be on?

**Comment by wwieder** [comment]
actually, this one would be relatively easy to bring in, as #2365 does 70% of what we need to do for MIMICS modifications.  It would have to be on an answer changing tag.

**Comment by slevis-lmwg** [comment]
@wwieder #2365 currently says that it will close this issue. Is that ok with you or should this issue remain open?

**Comment by wwieder** [comment]
Yes, this issue is fine to close
