### ISSUE TITLE
New population dataset for streams files?

### ISSUE THREAD

**Issue by adrifoster** [ESCOMP/CTSM#2701]
TRENDY gave us a new population dataset (which is used in our fire models).

It's located `/glade/derecho/scratch/afoster/TRENDY_2024/inputs/pop/[population.nc](http://population.nc/)` right now. Compare to the default dataset we currently use which is `/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/firedata/clmforc.Li_2017_HYDEv3.2_CMIP6_hdm_0.5x0.5_AVHRR_simyr1850-2016_c180202.nc`

The old dataset only goes to 2016, whereas this new one goes out to 2023. Both are derived from HYDE. (HYDE 3.4 for the new one; HYDE 3.2 for our old one).

Should we update this at some point? @lifang0209 did you make this dataset?

@wwieder @lawrencepj1

**Comment by ekluzek** [comment]
In the CTSM SE meeting this morning we decided we would NOT bring this in for ctsm5.3.0 and likely not for this years TRENDY.

But, bringing this in as a ctsm6.0.0 type update would be a good thing to do. It won't change answers enough for it to be a problem to bring in alongside other tuning changes. There's not time to get it done for ctsm5.3.0.

**Comment by lifang0209** [comment]
@adrifoster  It's important to extend the forcing data period to 2023 to correctly simulate the changes in human ignitions and suppression effects during 2016-2023.  I have HYDE3.3.  I could made new population density data for CLM6/CTSM6 based on HYDE3.4, but I cannot find it at the path you provided (/glade/derecho/scratch/afoster/TRENDY_2024/inputs/pop/population.nc).

**Comment by adrifoster** [comment]
> @adrifoster It's important to extend the forcing data period to 2023 to correctly simulate the changes in human ignitions and suppression effects during 2016-2023. I have HYDE3.3. I could made new population density data for CLM6/CTSM6 based on HYDE3.4, but I cannot find it at the path you provided (/glade/derecho/scratch/afoster/TRENDY_2024/inputs/pop/population.nc).

Sorry @lifang0209 I moved it to `/glade/campaign/cgd/tss/projects/TRENDY2024/inputs/pop/population.nc` for long-term since it was in my scratch.

If you are able to update our population streams data that would be great!

**Comment by ekluzek** [comment]
This is something we need to do for CMIP7 simulations, so should do as part of the CTSM5.4 minor version update.

**Comment by lifang0209** [comment]
@ekluzek Hi Erik, 
The global 0.5-degree annual population density dataset (1850-2023) derived from HYDE3.4 population data is at:
/glade/derecho/scratch/fangli/hdm1850-2023-FangLi-250211.nc

Data processing methods:
Temporal:
1850-1949: Linearly interpolated from HYDE3.4 decadal population data
1950-2023: Directly from HYDE3.4 annual population data
Spatial:
All data regridded from HYDE3.4 5-minute resolution to 0.5 degree
Then, I derived population density (variable: hdm) by dividing population data by land  area

![Image](https://github.com/user-attachments/assets/dd77faac-e0de-40bc-96b5-b934ea9e7e8d)

![Image](https://github.com/user-attachments/assets/7c50d0f3-dd32-4dc7-884a-88a0a9560988)

![Image](https://github.com/user-attachments/assets/85333fd9-3b6e-4057-9b6f-3124d962e91b)

Fang

**Comment by lifang0209** [comment]
CMIP7 population density forcing data is currently unavailable and marked as unknown and TBD, see below

<img width="866" alt="Image" src="https://github.com/user-attachments/assets/ba6ce12b-2846-4a8e-92ac-c70b8e8234f8" />

**Comment by wwieder** [comment]
Let's get this ready to integrate for ctsm5.4, but should do a transient run comparing hyde 3.2 and 3.4 results to evaluate effects on burned area.

**Comment by lifang0209** [comment]
I can run a present-day comparison between HYDE3.2 and HYDE3.4 to check the differences if needed.
Have you decided to use CRUJRA as the default forcing dataset for CTSM6?

**Comment by wwieder** [comment]
Thanks for this offer, @lifang0209. I don't know how critical it is to do this simulation right now?  Maybe wait a bit until we're getting closer to having full datasets for a CTSM5.4 minor version tag?  

Yes, we are planning on using CRUJRA as our default datm dataset for CLM6.  @slevis-lmwg almost has a tag ready to create this compset out of the box

**Comment by lifang0209** [comment]
@wwieder I conducted two comparative simulations using CURJRA with the new (HYDE3.4) and old (HYDE3.2) datasets. The influence is small, with the global burned area decreasing by only 0.05%. Spatially, the change in the 2000–2014 average annual burned area fraction (%/yr) is mostly within the range of -1~+1%/yr (see the plot below).

![Image](https://github.com/user-attachments/assets/66d1a078-df46-4218-a2d2-225e3bbdbb6d)

**Comment by wwieder** [comment]
Thanks for checking on this, Fang. After the LMWG maybe you can help us evaluate fire fluxes in CLM and CESM3_beta runs?

**Comment by ekluzek** [comment]
It looks like we didn't have any future lightning data for the SSP scenarios. So can you confirm that will still be the case for CMIP7 and we'll just use the historical dataset?

**Comment by ekluzek** [comment]
Deleting my last comment, as it was posted in the wrong place. And will add a new comment about the future scenarios.

**Comment by ekluzek** [comment]
@lifang0209 for the future scenarios we will need population density data for each of the CMIP7 SSP scenarios. Is this something you can help us with? Or is there someone else we should work with to get the data for us? @lawrencepj1 do you know about the future scenario data for population density?

**Comment by lifang0209** [comment]
Currently, the population density dataset I developed based on HYDE3.4 is the only one available that extends to 2022 (the end year of the CMIP7 historical run). However, HYDE3.4 does not provide future population density data.

One potential option is to extend the dataset by combining the future population density changes I previously created using HYDE3.2 with the HYDE3.4 dataset. This approach could provide a continuous dataset covering 1850–2100.

There will be a CMIP discussion on March 20 regarding this topic, and I may have more information to share after the meeting.

**Comment by lifang0209** [comment]
@ekluzek Thanks for your suggestion! I have copied the file to /glade/work/fangli/hdm1850-2023-FangLi-250211.nc

**Comment by ekluzek** [comment]
Thanks so much for that update @lifang0209@. We'll just wait for CMIP7 to release the new future scenario data. So we'll just work on getting in this historical update for now.

**Comment by ekluzek** [comment]
Moving this out of the ctsm5.4.0 milestone.

**Comment by wwieder** [comment]
Sorry, I haven't followed this whole thread, but are there new population density data in the CMIP7 data @lawrencepj1 is going to be processing for the CTSM 5.4 tag?  I seems like we should have an issue related to population density with the 5.4 milestone?

**Comment by dlawrenncar** [comment]
I think in principle there should be new population datasets, but what is
happening is unclear.  Here
<https://input4mips-cvs.readthedocs.io/en/latest/dataset-overviews/population/>is
the CMIP7 page for population density, which shows no leads.  But, a
github discussion
thread <https://github.com/PCMDI/input4MIPs_CVs/discussions/188>implies at
least a small amount of activity.

**Comment by ekluzek** [comment]
@wwieder this isn't data that Peter processes. And it's NOT part of the data that we've currently got from CMIP7. Which is why I moved the milestone. 

We'll likely get help from @lifang0209 for bringing it into CESM when it is available. @lifang0209 do you know anything beyond what @dlawrenncar talks about above?

**Comment by wwieder** [comment]
I'm totally confused now. 

The link Dave provided above includes an email from Fang that actually references this issue and the 1850-2023 datasets Fang derived from the HYDE3.4 dataset.  This makes me think this IS a candidate for the CMIP7 population density dataset?  I'm going to add the ctsm.5.4.0 milestone back here until this is clear up and we know if there's an official CMIP7 dataset we should be including in our minor version release.

**Comment by lifang0209** [comment]
Three groups developed future population datasets. CMIP7 is still discussing which dataset will be used and how to link with the HYDE historical data. They want a population dataset that not only harmonizes historical and future population but also harmonizes with land use data and urban information, and will be used not only for ESMs but also for IAMs (IAMs need high resolution).

**Comment by wwieder** [comment]
Thanks for the additional details, Fang. Erik, thanks for helping me understand that this isn't critical for the 5.4 minor version tag.  I'll change the milestone accordingly

**Comment by lifang0209** [comment]
@ekluzek Hi Erik, the new historical population density data is located at /glade/u/home/fangle/clmforc.Li_2025_CMIP7_hdm_0.5x0.5_simyr1850-2100_c250717.nc 

Details about the data:
The hdm for 1850–2025 is based on CMIP7 forcing:
/data/feikc/data/cmip7_inputdata/hist/pop-dens_input4MIPs_population_CMIP_PIK-CMIP-1-0-0_gr_1850-2025.nc.
After 2025, the hdm remains the same as in CMIP6. CMIP7 population density for future scenarios is still under preparation.

You can extract the hdm for the historical period as needed for CTSM6/CESM3.

The figure below shows the spatial pattern of CMIP7 and CMIP6 population densities for 2000-2010

<img width="2252" height="814" alt="Image" src="https://github.com/user-attachments/assets/aeb8cdae-6bbb-468e-8315-54449b36d87f" />

**Comment by wwieder** [comment]
Thanks for posting this @lifang0209.  A few questions for Fang:

1. Can you easily show the diffs between the CMIP6 and CMIP7 datasets for the time period above (or are the data identical to what you showed in the diffs between HYDE3.4 and HYDE3.2, further up this thread)?
2. Are there any other important changes to population density over this historical period that we should know about?
3. What do you mean by "_After 2025, the hdm remains the same as in CMIP6_"?  Does this mean the future scenarios on your raw file correspond of a particular CMIP6 SSP?  If so, which one?
4. Are these the 'final' CMIP7 historical data?

Second round of questions on the CTSM/CESM side:

5. Assuming these are the final CMIP7_HIST data, should we include this in the 5.4 milestone to create new historical surface datasets?
6. Are we better off truncating this file in 2025 to avoid confusion about CMIP7 scenarios that are forthcoming?

**Comment by lifang0209** [comment]
@wwieder Thanks for the questions.
1. The figure below shows the difference between CMIP6 and CMIP7 (CMIP7 - CMIP6 for 2000–2010). Note that the CMIP7 population density differs from HYDE3.4 (HYDE3.4 is used in TRENDY) for the present-day period.

<img width="3043" height="1857" alt="Image" src="https://github.com/user-attachments/assets/3101b744-84f7-420e-b113-5c9350cca865" />

The timeseries for CMIP7 and CMIP6

<img width="1963" height="1170" alt="Image" src="https://github.com/user-attachments/assets/f323dc38-0b99-4ab4-8505-2f5ecb1bfb73" />

2. The 1850–2025 population density in the provided data is the official CMIP7 population density forcing.
3. The new data I provided is based on /glade/campaign/cesm/cesmdata/cseg/inputdata/lnd/clm2/firedata/clmforc.Li_2018_SSP3_CMIP6_hdm_0.5x0.5_AVHRR_simyr1850-2100_c181205.nc  (so it's CMIP6's SSP3), but I replaced the hdm for 1850–2025 with CMIP7 data. The CMIP7 future hdm is not yet available. They are still working on it.
4. The hdm for 1850–2025 is based on the officially released CMIP7 historical population density data.

5. It's time-varying, so it's not in the surface dataset but in firedata. If the model is used for CMIP7, it might be better to include the CMIP7 hdm in the 5.4 milestone, but the decision is yours. :)
6.  Yes, I agree that it's better to truncate this file in 2025.

**Comment by wwieder** [comment]
OK, thanks for clarifying this, @lifang0209, your response if helpful and clear.

@slevis-lmwg can you bring this into our workflow for the 5.4 tag?  (even though population data comes in as a stream file)

Is there more we need to do WRT to preprocessing scripts to be consistent with other CMIP7 datasets that @lawrencepj1 has used?

I'll start a brainstorm for definition of done here:

- [x] create and name a clean file for historic population from CMIP7 raw data (ready to 2025 but not beyond, yet, and we will consider doing this for the clm6 release)
- [x] commit the script for above the appropriate repo (to be addressed in #3352)
- [x] rimport the new CMIP7 historic dataset (to be addressed in #2851)
- [x] set defaults namelist for CLM6 to point to this CMIP7_hist data (to be addressed in #3361)
- [x] preserve option to use HYDE3.4 data (for use in TRENDY) and make sure file names and metadata are clear (the corresponding TRENDY2025 data are added manually, so this is a moot point)
- [x] brainstorm if we want any bridge options to enable future scenarios before CMIP7_scenario data are available.

**Comment by slevis-lmwg** [comment]
I copied (not renamed nor ./rimport-ed yet)
`~fangli/clmforc.Li_2025_CMIP7_hdm_0.5x0.5_simyr1850-2100_c250717.nc`
to
`/glade/campaign/cesm/cesmdata/cseg/inputdata/lnd/clm2/firedata`

**Comment by slevis-lmwg** [comment]
I'm renaming the popdens file to
`clmforc.Li_2025_CMIP7_SSP3CMIP6_hdm_0.5x0.5_simyr1850-2100_c250717.nc`
based on @lifang0209's description above.

**Comment by wwieder** [comment]
Raw data from CMIP7 are here 

/glade/campaign/cesm/cesmdata/input4MIPs_raw/input4MIPs/CMIP7/CMIP/PIK/PIK-CMIP-1-0-0

Is there a script we can archive that translated these raw data into the forcing file Fang generated?

**Comment by slevis-lmwg** [comment]
I emailed @lifang0209 to request this.

**Comment by lifang0209** [comment]
@slevis-lmwg  I sent you my NCL script by email

**Comment by wwieder** [comment]
Thank you!

**Comment by slevis-lmwg** [comment]
Closing as done (or moved to future work).
